name: testing
on: 
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    testing:
        steps:
        - name: .NET Core CLI
           uses: baruchiro/github-actions@0.0.1
